nuus/debug/__init__.py
from flask import Blueprint, url_for, render_template, request, redirect, session, g, abort, flash, current_app, Response

import gzip
import nuus
from nuus import usenet, usenet_pool
from nuus.database import engine, tables
from nuus.utils import parse_date, date_deltas
from nuus.views import get_user
from nuus.indexer import decoder
import nntplib
import os
import pickle
from pprint import pprint
import re
from sqlalchemy.sql import select, bindparam
import sys
import time

__all__ = ['blueprint']

blueprint = Blueprint('debug', __name__, url_prefix='/debug')

BLOCK_STORAGE_DIR = nuus.app.config.get('BLOCK_STORAGE_DIR')
BLOCK_FILE_REGEX = re.compile(nuus.app.config.get('BLOCK_FILE_REGEX'))

def get_all_files():
    groups = {}
    for fn in os.listdir(BLOCK_STORAGE_DIR) + os.listdir(os.path.join(BLOCK_STORAGE_DIR, 'complete')):
        m = BLOCK_FILE_REGEX.match(fn)
        if m:
            group = m.group('group')
            if not (group in groups):
                groups[group] = []
            groups[group].append((int(m.group('start')), fn))
    for group in groups:
        groups[group] = sorted(groups[group])
    return groups

@blueprint.route('/pages')
def list_pages():
    return render_template('debug/pages.html', groups=get_all_files(), user=get_user())

@blueprint.route('/nextfile')
def get_next_file():
    filename = request.args.get('filename')
    filter = request.args.get('filter')
    groups = get_all_files()
    m = BLOCK_FILE_REGEX.match(filename)
    group = m.group('group')
    start = int(m.group('start'))
    for n,fn in groups[group]:
        if n > start:
            return redirect(url_for('.dump_articles', filename=fn, filter=filter))
    return redirect(url_for('.list_pages'))

@blueprint.route('/prevfile')
def get_prev_file():
    filename = request.args.get('filename')
    filter = request.args.get('filter')
    groups = get_all_files()
    m = BLOCK_FILE_REGEX.match(filename)
    group = m.group('group')
    start = int(m.group('start'))
    prev = None
    for n,fn in groups[group]:
        if n >= start:
            return redirect(url_for('.dump_articles', filename=prev, filter=filter))
        prev = fn
    return redirect(url_for('.list_pages'))

@blueprint.route('/dump')
def dump_articles():
    filename = request.args.get('filename')
    group = request.args.get('group')
    filter = request.args.get('filter')
    if filename is None and group is None:
        flash('filename or group expected', 'danger')
        return redirect(url_for('.list_pages'))
    if filename is not None:
        files = [filename]
    else:
        groups = get_all_files()
        files = [fn for n,fn in groups[group]]
    articles = []
    for filename in files:
        fn = os.path.join(BLOCK_STORAGE_DIR, filename)
        if not os.path.exists(fn):
            fn = os.path.join(BLOCK_STORAGE_DIR, 'complete', filename)
            if not os.path.exists(fn):
                flash('file ' + filename + ' does not exist', 'danger')
                return redirect(url_for('.list_pages'))
        with gzip.open(fn, 'r') as f:
            articles += pickle.load(f)
    _articles = []
    while len(articles):
        n, a = articles.pop(0)
        a['subject'] = os.fsencode(a['subject']).decode('latin-1')
        if filter is None or filter in a['subject']:
            _articles.append(a)
        
    return render_template('debug/articles.html', filename=filename, group=None, filter=filter, articles=_articles, user=get_user())

@blueprint.route('/article')
def get_article():
    message_id = request.args.get('message_id')
    if message_id is None:
        flash('message_id required', 'danger')
        return redirect(request.referrer)
    # check cache
    cfn = os.path.join(BLOCK_STORAGE_DIR, 'cache', message_id[1:-1])
    #if os.path.exists(cfn):
    #    with gzip.open(cfn, 'r') as f:
    #        rval = f.read()
    #    return rval
    u = usenet.Usenet(connection_pool=usenet_pool)
    lines = u.get_article(message_id)
    rval = decoder.decode(lines)
    with gzip.open(cfn, 'w') as f:
        f.write(rval)
    return Response(rval, content_type='text/plain')

nuus/views.py
from flask import Blueprint, url_for, render_template, request, redirect, session, g, abort, flash, current_app, Response
from hashlib import md5
from nuus.utils import humanize_date_difference
from nuus.database import engine, tables
from nuus import nzb
import os
import re
from sqlalchemy.sql import select, or_, func

__all__ = ['blueprint']

blueprint = Blueprint('nuus', __name__)

def get_user(user_id=None):
    if user_id is None:
        user_id = session.get('user_id')
    if user_id is None:
        return None
    conn = engine.connect()
    sel = select([tables.users]).where(tables.users.c.id == user_id)
    user = conn.execute(sel).fetchone()
    conn.close()
    return user

def md5hash(s):
    m = md5()
    m.update(s.encode())
    return m.hexdigest()

def humanize_size(s):
    p = ['bytes', 'KB','MB','GB','TB']
    while s > 1024 and len(p) > 1:
        s /= 1024
        p = p[1:]
    return '{0:.2f} {1}'.format(s, p[0])

@blueprint.route('/logout')
def logout():
    session.pop('user_id')
    return redirect(url_for('.index'))

@blueprint.route('/', methods=['GET','POST'])
def index():
    query = request.args.get('query')
    offset = request.args.get('offset')
    limit = request.args.get('limit')
    rd_offset = offset
    rd_limit = limit
    offset = int(offset) if offset else 0
    limit = int(limit) if limit else 25
    user = get_user()
    if request.method == 'POST':
        username = request.form.get('username')
        if username is not None:
            password = md5hash(request.form.get('password', ''))
            conn = engine.connect()
            sel = select([tables.users]).where(tables.users.c.username == username)
            user = conn.execute(sel).fetchone()
            if user is None and username in current_app.config.get('VALID_USERS'):
                conn.execute(tables.users.insert(), username=username,password=password)
                user = conn.execute(sel).fetchone()
            elif user is not None and user['password'] != password:
                user = None
            if user is not None:
                session['user_id'] = user['id']
            else:
                flash('invalid username or password', 'danger')
            conn.close()
        sabnzbd_host = request.form.get('sabnzbd_host')
        if sabnzbd_host:
            sabnzbd_apikey = request.form.get('sabnzbd_apikey')
            conn = engine.connect()
            conn.execute(tables.users.update().values(dict(
                sabnzbd_host=sabnzbd_host,
                sabnzbd_apikey=sabnzbd_apikey
            )))
            conn.close()
        return redirect(url_for('.index', query=query,offset=rd_offset,limit=rd_limit))
    user = get_user()
    releases = []
    total_results = 0
    if 'user_id' in session and query:
        conn = engine.connect()
        total_results = conn.execute(select([func.count(),tables.releases]).where(tables.releases.c.name.like('%%%s%%' % query))).scalar()
        sel = select([tables.releases]).where(tables.releases.c.name.like('%%%s%%' % query)).order_by(-tables.releases.c.date).limit(limit).offset(offset)
        res = conn.execute(sel)
        for row in res.fetchall():
            release = dict(row)
            sel = select([tables.release_groups.c.group]).where(tables.release_groups.c.release_id == release['id']).distinct()
            groups = [x[0] for x in conn.execute(sel).fetchall()]
            release['groups'] = groups
            age = humanize_date_difference(release['date'])
            release['age'] = age
            release['size'] = humanize_size(release['size'])
            releases.append(release)
        res.close()
        conn.close()
    return render_template('index.html', user=user, query=query, results=releases, total_results=total_results, offset=offset, limit=limit)


@blueprint.route('/nzb/<int:release_id>.nzb')
def get_nzb(release_id):
    return Response(nzb.create_nzb(release_id), mimetype='application/x-nzb')
    # http://wiki.sabnzbd.org/api#toc28
    # http://miffy:9095/api?mode=addurl&apikey=d96490fab5f6e61b8fafd66e50886c26&name=http://localhost:5000/nzb/1000.nzb&nzbname=test

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Nuus</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" media="screen">
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap-glyphicons.css') }}" rel="stylesheet" media="screen">
  </head>
  <body>
    <div class="container">
      <div class="navbar navbar-static-top">
        <a class="navbar-brand" href="#">Nuus</a>
        <ul class="nav navbar-nav">
          {% set active_nav = active_nav|default('index') -%}
          <li{% if active_nav == 'index' %}  class="active"{% endif %}><a href="{{ url_for('nuus.index') }}">Home</a></li>
          <li{% if active_nav == 'debug' %} class="active"{% endif %}><a href="{{ url_for('debug.list_pages') }}">Debug</a></li>
        </ul>
        <ul class="pull-right nav navbar-nav">
          {% if not user %}
          <li><a data-toggle="modal" href="#signInModal">Sign In</a></li>
          {% else %}
          <li><a data-toggle="modal" href="#optionsModal"><span class="glyphicon glyphicon-cog"></span></a></li>
          <li><a data-toggle="modal" href="{{ url_for('nuus.logout') }}"><span class="glyphicon glyphicon-off"></span></a></li>
          {% endif %}
        </ul>
      </div>
      <div class="alerts">
      {% with messages = get_flashed_messages(with_categories=True) %}
      {% for cat,msg in messages %}
      <div class="alert alert-{{ cat }}">
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	{{ msg }}
      </div>
      {% endfor %}
      {% endwith %}
      </div>
      {% block content %}
      {% endblock content %}
    </div>
    {% if user %}
    <div class="modal fade" id="optionsModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Options</h4>
          </div>
          <form id="optionsForm" method="post">
            <div class="modal-body">
              <div class="form-group">
                <label for="inputHost">Sabnzbd host URL</label>
                <input type="text" class="form-control" name="sabnzbd_host" id="inputHost" placeholder="URL..." value="{{ user.sabnzbd_host }}">
              </div>
              <div class="form-group">
                <label for="inputAPIKey">Sabnzbd API Key</label>
                <input type="text" class="form-control" name="sabnzbd_apikey" id="inputAPIKey" placeholder="API Key..."{% if user.sabnzbd_apikey %} value="{{ user.sabnzbd_apikey }}"{% endif %}>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </form>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    {% else %}
    <div class="modal fade" id="signInModal" data-backdrop="static">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Sign In</h4>
          </div>
          <form id="signInForm" method="post">
            <div class="modal-body">
              <div class="form-group">
                <label for="inputUsername">Username address</label>
                <input type="text" class="form-control" name="username" id="inputUsername" placeholder="Username...">
              </div>
              <div class="form-group">
                <label for="inputPassword">Password</label>
                <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password...">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Sign In</button>
            </div>
          </form>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    {% endif %}
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/jquery.bootstrap-growl.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/nuus.js') }}"></script>
    <script type="text/javascript">
      {% if not user %}
      $(function() { $("#signInModal").modal('show'); });
      {% else %}
      sabnzbd = {
      host: "{{ user.sabnzbd_host }}",
      apikey: "{{ user.sabnzbd_apikey }}"
      };
      {% endif %}
    </script>
  </body>
</html>

templates/cache.html
{% extends 'base.html' %}
{% block content %}
<div class="row-fluid">
  <ul class="nav nav-pills">
    {% for grp in cached_groups %}
    <li{% if grp == group %} class="active"{% endif %}>
      <a href="{{ url_for('.cache', group=grp) }}">{{ grp }}</a>
    </li>
    {% endfor %}
  </ul>
  {% if caches is defined %}
  <div class="pagination">
    <ul>
      <li><a href="#">&laquo;</a></li>
      {% for c in caches %}
      <li{% if c == page %} class="disabled"{% endif %}><a href="{{ url_for('.cache', group=group, page=c) }}">{{ c }}</a></li>
      {% endfor %}
      <li><a href="#">&raquo;</a></li>
    </ul>
  </div>
  {% endif %}
  {% if articles is defined %}
  <div>
    <table class="table table-striped">
      <thead>
        <tr>
	  <th>#</th>
          <th>Poster</th>
          <th>Date</th>
          <th>Article ID</th>
          <th>Size</th>
        </tr>
      </thead>
      <tbody>
      {% for a in articles %}
      <tr>
	<td colspan="5">{{ a[1] }}</td>
      </tr>
      <tr>
	<td>{{ a[0] }}</td>
	<td>{{ a[2] }}</td>
	<td>{{ a[3] }}</td>
	<td>{{ a[4] }}</td>
	<td>{{ a[6] }}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% endif %}
</div>
{% endblock %}

templates/files.html
{% extends 'base.html' %}
{% block content %}
<div class="row-fluid">
{% for file in files %}
<div>{{ file.id }}</div>
{% endfor %}
</div>
{% endblock %}

templates/groups.html
{% extends 'base.html' %}
{% block content %}
<div class="row-fluid">
{% for group in groups %}
<div>{{ group }}</div>
{% endfor %}
<form class="form-inline" method="POST">
  <input type="text" name="group" placeholder="Add Group...">
  <button type="submit" class="btn"><i class="icon-plus"></i></button>
</form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
  <form class="form-inline">
    <div class="col-lg-11">
      <input type="text" class="form-control" name="query" placeholder="Search..."{% if query %} value="{{ query }}"{% endif %}/>
    </div>
    <button type="submit" class="btn btn-default">Search</button>
  </form>

  {% if results %}
  <p></p>
  <div class="text-right"><small>{% if offset > 1 %}<a href="{{ url_for('.index', query=query, offset=offset-(results|count),limit=(results|count)) }}">&laquo;</a> {% endif %}showing {{ offset+1 }} - {{ offset + (results|count) }} of {{ total_results }} results{% if offset + (results|count) < total_results %} <a href="{{ url_for('.index', query=query, offset=offset+(results|count),limit=(results|count)) }}">&raquo;</a>{% endif %}</small></div>
  <table class="table table-hover table-condenced">
    <thead><td>Name</td><td></td><td>Files</td><td>Size</td><td>Group(s)</td><td>Age</td></thead>
    {% for r in results %}
    <tr>
      <td><small><b>{{ r.name }}</b></small></td>
      <td style="width: 55px;">
        <a data-toggle="tooltip" title="download nzb" href="{{ url_for('.get_nzb', release_id=r.id) }}"><i class="glyphicon glyphicon-download"></i></a>
        {% if user.sabnzbd_apikey %}
        <a data-toggle="tooltip" title="send to sabnzbd" href="#" data-nzbname="{{ r.name }}" data-name="{{ url_for('.get_nzb', release_id=r.id,_external=True) }}"><img src="{{ url_for('static', filename='vendor/sabnzbd/download.png') }}"></i></a>
        {% endif %}
      </td>
      <td>
        <small style="color: #3da233">{{ r.file_count }} Files</small><small style="color: #e2a910">{% if r.nfo_file_id %} | 1 NFO{% endif %}{% if r.archive_file_count %} | {{ r.archive_file_count }} ARCHIVE{% endif %}{% if r.par2_file_count %} | {{ r.par2_file_count }} PAR2{% endif %}{% if r.nzb_file_id %} | 1 NZB{% endif %}</small>
      </td>
      <td><small>{{ r.size }}</small></td>
      <td><small>{% for g in r.groups %}{{ g }}{% if not loop.last %}, {% endif %}{% endfor %}</small></td>
      <td><small>{{ r.age }}</small></td>
    </tr>
    {% endfor %}
  </table>
  {% endif %}
{% endblock %}

templates/nzbs.html
{% extends 'base.html' %}
{% block content %}
<div class="row-fluid">
{% for file in nzbs %}
<div>{{ file.id }}</div>
{% endfor %}
</div>
{% endblock %}

templates/releases.html
{% extends 'base.html' %}
{% block content %}
<div class="row-fluid">
  {% for release in releases %}
  <h4>{{ release.id }}</h4>
  {% for file in release.files %}{{ file.filename }} {% endfor %}
  {% endfor %}
</div>
{% endblock %}

templates/status.html
{% extends 'base.html' %}
{% block content %}
<div class="row-fluid">
  {% for group in groups %}
  <h4>{{ group.id }}</h4>
  {% if group.status == 'pending' %}
  <p>Waiting...</p>
  {% elif group.status == 'updating' %}
  <p>Updating: {{ group.progress }}% complete</p>
  {% else %}
  <p>Finished!</p>
  {% endif %}
  {% endfor %}
</div>
{% endblock %}